---
- name: Installing mysqlserver 
  ansible.builtin.dnf:
    name: mysql-server
    state: present
  
- name: Installing pymsql
  ansible.builtin.pip:
    name: PyMySQL
    state: present    
- name: Enable and start mysql-server(mysqld)
  ansible.builtin.service:
    enabled: yes
    state: started
    name: mysqld

- name: connect to mysql server
  community.mysql.mysql_info:
    login_user: root
    login_password: "ExpenseApp@1"
    login_host: "172.31.30.42"
  register: mysql_info
  ignore_errors: true  

- name: printing mysql_info
  ansible.builtin.debug:
    msg: "{{mysql_info}} "  

- name: Setting root password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass ExpenseApp@1"    
  when: mysql_info.failed is true