- name: Deleting directory
  ansible.builtin.file:
    path: "{{APP_PATH}}"  
    state: absent 

- name: Creating directory
  ansible.builtin.file:
    path: "{{APP_PATH}}"      
    state: directory 

- name: unarchiving code
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{COMPONENT}}-v2.zip
    dest: "{{APP_PATH}}"  
    remote_src: yes